- include: apt.yml
  when: ansible_pkg_mgr == 'apt'

- include: yum.yml
  when: ansible_pkg_mgr == 'yum'

- name: setup postgres db
  sudo_user: postgres
  postgresql_db: name={{ item }}
  with_items: "{{ db_names }}"

- name: setup postgres users
  sudo_user: postgres
  postgresql_user: "name={{ db_user }} role_attr_flags=NOSUPERUSER,CREATEDB,LOGIN password={{ db_password }}"

- name: setup lab-assistant user permissions
  sudo_user: postgres
  postgresql_user: "db={{ item }} name={{ db_user }} priv=ALL"
  with_items: "{{ db_names }}"