- name: create app user group
  group: name="{{ app_user }}" system=yes

- name: create app user
  user: name="{{ app_user }}" group="{{ app_user }}" system=yes

- name: check out app from version control
  git: repo="{{ repo_url }}" clone=yes version="{{ git_sha }}" dest="{{ app_path }}" force=yes

- name: ensure app dir is owner by app user
  file: path="{{ app_path }}" owner="{{ app_user }}" group="{{ app_user }}" recurse=yes

- name: create logs dir
  file: path="{{ logs_dir }}" state=directory owner="{{ app_user }}" group="{{ app_user }}"

- name: create pids dir
  file: path="{{ pids_dir }}" state=directory owner="{{ app_user }}" group="{{ app_user }}"

- name: install pslist
  apt: name=pslist

- name: upload init script
  template: src=project-m_init.j2 dest=/etc/init.d/project-m mode=0755

- name: upload config
  template: src=config.json.j2 dest="{{ app_path }}/config/config.json" mode=0600

- name: install npm dependencies
  become_user: "{{ app_user}}"
  command: npm install chdir="{{ app_path }}"

- name: re/start project-m
  service: name=project-m enabled=yes state=restarted
